version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ziyokor-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: work_control
    ports:
      - "5432:5432"
    volumes:
      - ziyokor-db-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

volumes:
  ziyokor-db-data:
